[[constraint]]
  revision = "a43f7a959840d59c29cce9a39174415f19d61096"
  name = "github.com/ziutek/glib"

[[constraint]]
  revision = "7d16e692318bf950d4eee95a008ae252adca4a65"
  name = "github.com/ziutek/gst"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
